package secdrill.controlplane.evidence

import org.slf4j.LoggerFactory
import org.springframework.beans.factory.SmartInitializingSingleton
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.core.env.Environment
import org.springframework.jdbc.core.simple.JdbcClient
import org.springframework.stereotype.Component
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import secdrill.controlplane.access.OwnedResource
import secdrill.controlplane.access.OwnershipGuard
import secdrill.controlplane.access.ResourceNotFoundException
import secdrill.controlplane.identity.LearnerPrincipal
import secdrill.kernel.ApiException
import secdrill.kernel.ArtifactSensitivity
import secdrill.kernel.Digests
import secdrill.kernel.ErrorCode
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.time.Clock
import java.time.Duration
import java.time.Instant
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.temporal.ChronoUnit
import java.util.UUID

/** Private byte store (11). Keys are generated by the platform, never taken from users. */
interface ArtifactStore {
    fun put(key: String, bytes: ByteArray)
    fun get(key: String): ByteArray?
    fun delete(key: String)
}

/**
 * Local-filesystem store for development and tests only. Production needs the S3-compatible private store
 * (not implemented, D-15); [ArtifactStoreSafetyCheck] refuses this store under `prod`.
 */
class LocalArtifactStore(private val root: Path) : ArtifactStore {
    private fun resolve(key: String): Path {
        require(Regex("^[a-z]+(/[0-9a-f-]{36})+$").matches(key)) { "invalid artifact key" }
        return root.resolve(key).normalize().also { require(it.startsWith(root)) { "artifact key escapes the store" } }
    }

    override fun put(key: String, bytes: ByteArray) {
        val target = resolve(key)
        Files.createDirectories(target.parent)
        val temp = Files.createTempFile(target.parent, ".upload", ".tmp")
        Files.write(temp, bytes)
        Files.move(temp, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
    }

    override fun get(key: String): ByteArray? = resolve(key).takeIf(Files::exists)?.let(Files::readAllBytes)

    override fun delete(key: String) {
        Files.deleteIfExists(resolve(key))
    }

    /** Store keys with their last-modified time, for the orphan sweep (T14). S3 enumeration is separate (D-15). */
    fun list(): List<Pair<String, java.time.Instant>> {
        if (!Files.isDirectory(root)) return emptyList()
        return Files.walk(root).use { stream ->
            stream.filter(Files::isRegularFile).toList().mapNotNull { path ->
                val key = root.relativize(path).toString().replace('\\', '/')
                if (Regex("^[a-z]+(/[0-9a-f-]{36})+$").matches(key)) key to Files.getLastModifiedTime(path).toInstant() else null
            }
        }
    }
}

@ConfigurationProperties("secdrill.artifacts")
data class ArtifactProperties(val store: String = "local", val localDir: Path = Path.of(System.getProperty("java.io.tmpdir"), "secdrill-artifacts"))

@Configuration(proxyBeanMethods = false)
@EnableConfigurationProperties(ArtifactProperties::class)
class ArtifactStoreConfig {
    @Bean
    fun artifactStore(properties: ArtifactProperties): ArtifactStore {
        check(properties.store == "local") { "only the local development artifact store exists so far (D-15)" }
        return LocalArtifactStore(properties.localDir.toAbsolutePath().normalize())
    }
}

/** The local store keeps learner data on one host's disk without access control or versioning; never in prod. */
@Component
class ArtifactStoreSafetyCheck(private val environment: Environment, private val properties: ArtifactProperties) : SmartInitializingSingleton {
    override fun afterSingletonsInstantiated() {
        check(!("prod" in environment.activeProfiles && properties.store == "local")) {
            "Unsafe artifact configuration: the local artifact store must not run with 'prod'"
        }
    }
}

/** Retention by sensitivity (00, 14). Purging expired bytes is an operations job (T14). */
object RetentionPolicy {
    val EVIDENCE_METADATA: Duration = Duration.ofDays(180)

    fun artifactTtl(sensitivity: ArtifactSensitivity): Duration? = when (sensitivity) {
        ArtifactSensitivity.LEARNER, ArtifactSensitivity.PUBLIC_SUMMARY -> Duration.ofDays(180)
        ArtifactSensitivity.RAW_LOG -> Duration.ofDays(30)
        // Oracle material follows the content version lifecycle, not learner retention.
        ArtifactSensitivity.PRIVATE_ORACLE -> null
    }
}

data class ArtifactRef(
    val id: UUID,
    val sessionId: UUID,
    val key: String,
    val digest: String,
    val byteSize: Long,
    val mediaType: String,
    val sensitivity: ArtifactSensitivity,
    val expiresAt: Instant?,
)

data class ArtifactContent(val ref: ArtifactRef, val bytes: ByteArray)

/**
 * Session-scoped private artifacts (14). Rows carry digest, size, sensitivity and expiry; bytes live in the store.
 * Learner reads go through the owner guard, never return PRIVATE_ORACLE, treat deleted or expired artifacts as
 * missing, and refuse bytes whose digest no longer matches.
 */
@Service
class ArtifactService(
    private val jdbc: JdbcClient,
    private val store: ArtifactStore,
    private val guard: OwnershipGuard,
    private val clock: Clock,
) {
    private val log = LoggerFactory.getLogger(javaClass)

    /** Stores bytes for a Session. Bytes are written before the row; a rolled-back row leaves an orphan for the sweeper (T14). */
    @Transactional
    fun store(sessionId: UUID, sensitivity: ArtifactSensitivity, mediaType: String, bytes: ByteArray): ArtifactRef {
        val id = UUID.randomUUID()
        val key = "sessions/$sessionId/$id"
        val now = clock.instant().truncatedTo(ChronoUnit.MICROS)
        val ref = ArtifactRef(id, sessionId, key, Digests.sha256Hex(bytes), bytes.size.toLong(), mediaType, sensitivity,
            RetentionPolicy.artifactTtl(sensitivity)?.let { now.plus(it) })
        store.put(key, bytes)
        jdbc.sql(
            """INSERT INTO artifacts(id, session_id, object_key, digest, byte_size, media_type, sensitivity, expires_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        ).params(listOf(id, sessionId, key, ref.digest, ref.byteSize, mediaType, sensitivity.name, ref.expiresAt?.atOffset(ZoneOffset.UTC))).update()
        return ref
    }

    fun readForLearner(principal: LearnerPrincipal, artifactId: UUID): ArtifactContent {
        guard.requireOwned(principal, OwnedResource.ARTIFACT, artifactId)
        val ref = find(artifactId) ?: throw ResourceNotFoundException()
        val expired = ref.expiresAt?.let { !it.isAfter(clock.instant()) } ?: false
        if (ref.sensitivity == ArtifactSensitivity.PRIVATE_ORACLE || expired) throw ResourceNotFoundException()
        val bytes = store.get(ref.key) ?: throw ResourceNotFoundException()
        if (Digests.sha256Hex(bytes) != ref.digest) {
            log.error("Artifact {} failed digest verification; refusing to serve it", artifactId)
            throw ApiException(ErrorCode.INTERNAL_ERROR, "Internal error")
        }
        return ArtifactContent(ref, bytes)
    }

    /** Grader-side read (no learner principal): null when missing, deleted or failing its digest. */
    fun readInternal(artifactId: UUID): ArtifactContent? {
        val ref = find(artifactId) ?: return null
        val bytes = store.get(ref.key) ?: return null
        if (Digests.sha256Hex(bytes) != ref.digest) {
            log.error("Artifact {} failed digest verification", artifactId)
            return null
        }
        return ArtifactContent(ref, bytes)
    }

    private fun find(id: UUID): ArtifactRef? = jdbc.sql(
        "SELECT id, session_id, object_key, digest, byte_size, media_type, sensitivity, expires_at FROM artifacts WHERE id = ? AND deleted_at IS NULL",
    ).param(id).query { rs, _ ->
        ArtifactRef(
            rs.getObject(1, UUID::class.java), rs.getObject(2, UUID::class.java), rs.getString(3), rs.getString(4), rs.getLong(5),
            rs.getString(6), ArtifactSensitivity.valueOf(rs.getString(7)), rs.getObject(8, OffsetDateTime::class.java)?.toInstant(),
        )
    }.optional().orElse(null)
}
